import { evidenceRuntime, normalizeEvidencePolicy, type EvidenceSource } from './contractEvidence.ts';
import type { GeneratedContract } from './generate.ts';

type ObservationInput = {
  id: string;
  source: EvidenceSource;
};

export type ScalarOracleInput = ObservationInput & {
  valueField: string;
  /** Integer bounds in the same scaled unit as the observation. */
  lower: number;
  upper: number;
  decimals: number;
  resolutionTime: number;
};

export type OddsJournalInput = ObservationInput & {
  /** Projected field containing an array or JSON-encoded array of probabilities. */
  pricesField: string;
  outcomesField: string;
  outcomeLabels: string[];
  intervalSeconds?: number;
  maxSnapshots?: number;
  maxOverroundBps?: number;
};

function base(input: ObservationInput) {
  if (!/^[A-Z0-9_-]{4,64}$/.test(input.id)) throw new Error('Oracle id needs 4-64 uppercase letters, digits, hyphens or underscores.');
  const evidence = normalizeEvidencePolicy({ sources: [input.source] });
  if (input.source.format !== 'json' || !Object.keys(input.source.expect ?? {}).length) throw new Error('Observation oracles require JSON projection and at least one exact identity assertion.');
  return { id: input.id, evidence };
}

function field(source: EvidenceSource, name: string) {
  if (!Object.hasOwn(source.fields ?? {}, name)) throw new Error(`Missing projected field: ${name}.`);
}

const numericRuntime = `
def _scaled(value, decimals):
    # Exact base-10 parsing: no model arithmetic, booleans, NaN or exponents.
    if type(value) is bool or value is None:
        raise gl.vm.UserError("INVALID_NUMBER")
    text = str(value)
    negative = text.startswith("-")
    if negative:
        text = text[1:]
    parts = text.split(".")
    if len(parts) > 2 or not parts[0] or any(c not in "0123456789" for c in parts[0]):
        raise gl.vm.UserError("INVALID_NUMBER")
    fraction = parts[1] if len(parts) == 2 else ""
    if any(c not in "0123456789" for c in fraction) or len(fraction) > decimals or len(parts[0]) > 18:
        raise gl.vm.UserError("INVALID_PRECISION")
    result = int(parts[0]) * (10 ** decimals) + int((fraction + "0" * decimals)[:decimals] or "0")
    return -result if negative else result


def _observation(spec):
    evidence = _fetch_evidence(spec["evidence"])
    if not evidence[0]["available"]:
        raise gl.vm.UserError("[EXTERNAL] EVIDENCE_UNAVAILABLE")
    return json.loads(evidence[0]["content"]), evidence
`;

function emit(kind: string, spec: Record<string, unknown>, implementation: string): GeneratedContract {
  const className = `Gavel${kind}`;
  const source = `# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
# Generated by @gavel-sdk/core. Re-generate from the immutable specification.
import json
import hashlib
from datetime import datetime, timezone
from genlayer import *

SPEC_JSON = ${JSON.stringify(JSON.stringify(spec))}
${evidenceRuntime}
${numericRuntime}
class ${className}(gl.Contract):
${implementation}
    @gl.public.view
    def get_spec(self) -> str:
        return SPEC_JSON
`;
  return { className, source, compiledSpec: spec, filename: `${String(spec.id).toLowerCase()}_${kind.toLowerCase()}.py` };
}

/** Continuous complementary payout weights, not bucketed winners or asset transfers. */
export function generateScalarOracle(input: ScalarOracleInput): GeneratedContract {
  const common = base(input);
  field(input.source, input.valueField);
  if (![input.lower, input.upper].every(Number.isSafeInteger) || input.upper <= input.lower || Math.abs(input.lower) > 1e12 || Math.abs(input.upper) > 1e12) throw new Error('Scalar bounds must be ordered safe integers within +/- 1e12.');
  if (!Number.isSafeInteger(input.decimals) || input.decimals < 0 || input.decimals > 8) throw new Error('Scalar decimals must be 0-8.');
  if (!Number.isSafeInteger(input.resolutionTime) || input.resolutionTime < 1) throw new Error('Invalid resolutionTime.');
  const spec = { ...common, kind: 'SCALAR_OBSERVATION', valueField: input.valueField, lower: input.lower, upper: input.upper, decimals: input.decimals, resolutionTime: input.resolutionTime };
  return emit('ScalarOracle', spec, `    result_json: str

    def __init__(self):
        self.result_json = ""

    def _measure(self, spec: dict) -> dict:
        data, evidence = _observation(spec)
        value = _scaled(data[spec["valueField"]], spec["decimals"])
        bounded = max(spec["lower"], min(spec["upper"], value))
        long_bps = (bounded - spec["lower"]) * 10000 // (spec["upper"] - spec["lower"])
        return {"valueScaled": value, "longPayoutBps": long_bps, "shortPayoutBps": 10000 - long_bps,
                "evidence": evidence, "evidenceDigest": _digest(evidence)}

    def _verify_measurement(self, candidate: dict, spec: dict) -> bool:
        try:
            return candidate == self._measure(spec)
        except Exception:
            return False

    @gl.public.write
    def observe(self) -> None:
        if self.result_json:
            raise gl.vm.UserError("ALREADY_OBSERVED")
        spec = json.loads(SPEC_JSON)
        now = int(datetime.now(timezone.utc).timestamp())
        if now < spec["resolutionTime"]:
            raise gl.vm.UserError("OBSERVATION_NOT_OPEN")
        def leader():
            return self._measure(spec)
        def validator(result):
            return isinstance(result, gl.vm.Return) and self._verify_measurement(result.calldata, spec)
        result = dict(gl.vm.run_nondet_unsafe(leader, validator))
        result.update({"oracleId": spec["id"], "specHash": _digest(spec), "observedAt": now,
                       "kind": "SCALAR_OBSERVATION", "status": "OBSERVED", "transfersExecuted": False})
        self.result_json = _canonical(result)

    @gl.public.view
    def get_result(self) -> str:
        if not self.result_json:
            raise gl.vm.UserError("NOT_OBSERVED")
        return self.result_json

`);
}

/** Read-only market data journal. It does not adjudicate an event or create forecasts. */
export function generateOddsJournal(input: OddsJournalInput): GeneratedContract {
  const common = base(input);
  field(input.source, input.pricesField);
  field(input.source, input.outcomesField);
  if (!Array.isArray(input.outcomeLabels) || input.outcomeLabels.length < 2 || input.outcomeLabels.length > 16 || new Set(input.outcomeLabels).size !== input.outcomeLabels.length || input.outcomeLabels.some(label => typeof label !== 'string' || !label.trim() || label.length > 100)) throw new Error('Provide 2-16 unique outcome labels.');
  const intervalSeconds = input.intervalSeconds ?? 300;
  const maxSnapshots = input.maxSnapshots ?? 64;
  const maxOverroundBps = input.maxOverroundBps ?? 1000;
  if (!Number.isSafeInteger(intervalSeconds) || intervalSeconds < 60 || intervalSeconds > 86400) throw new Error('intervalSeconds must be 60-86400.');
  if (!Number.isSafeInteger(maxSnapshots) || maxSnapshots < 1 || maxSnapshots > 256) throw new Error('maxSnapshots must be 1-256.');
  if (!Number.isSafeInteger(maxOverroundBps) || maxOverroundBps < 0 || maxOverroundBps > 10000) throw new Error('Invalid maxOverroundBps.');
  const spec = { ...common, kind: 'ODDS_JOURNAL', pricesField: input.pricesField, outcomesField: input.outcomesField, outcomeLabels: input.outcomeLabels, intervalSeconds, maxSnapshots, maxOverroundBps };
  return emit('OddsJournal', spec, `    snapshots: TreeMap[u256, str]
    count: u256
    last_slot: u256

    def __init__(self):
        self.count = u256(0)
        self.last_slot = u256(0)

    def _quote(self, spec: dict) -> dict:
        data, evidence = _observation(spec)
        prices = data[spec["pricesField"]]
        labels = data[spec["outcomesField"]]
        if isinstance(prices, str):
            prices = json.loads(prices)
        if isinstance(labels, str):
            labels = json.loads(labels)
        if not isinstance(prices, list) or labels != spec["outcomeLabels"] or len(prices) != len(labels):
            raise gl.vm.UserError("INVALID_ODDS_OUTCOMES")
        probabilities = [_scaled(price, 8) for price in prices]
        if any(price < 0 or price > 100000000 for price in probabilities):
            raise gl.vm.UserError("INVALID_PROBABILITY")
        total = sum(probabilities)
        if total == 0:
            raise gl.vm.UserError("EMPTY_ODDS_BOOK")
        # Compare the unrounded margin: a display rounding must not cross the gate.
        coherent = abs(total - 100000000) <= spec["maxOverroundBps"] * 10000
        return {"outcomes": labels, "probabilitiesE8": probabilities,
                "overroundE8": total - 100000000, "coherent": coherent,
                "evidence": evidence, "evidenceDigest": _digest(evidence)}

    def _verify_quote(self, candidate: dict, spec: dict) -> bool:
        try:
            return candidate == self._quote(spec)
        except Exception:
            return False

    @gl.public.write
    def sample(self) -> None:
        spec = json.loads(SPEC_JSON)
        now = int(datetime.now(timezone.utc).timestamp())
        slot = now // spec["intervalSeconds"]
        if int(self.count) >= spec["maxSnapshots"]:
            raise gl.vm.UserError("JOURNAL_FULL")
        if self.count and slot <= int(self.last_slot):
            raise gl.vm.UserError("SLOT_ALREADY_SAMPLED")
        def leader():
            return self._quote(spec)
        def validator(result):
            return isinstance(result, gl.vm.Return) and self._verify_quote(result.calldata, spec)
        result = dict(gl.vm.run_nondet_unsafe(leader, validator))
        result.update({"oracleId": spec["id"], "specHash": _digest(spec), "observedAt": now,
                       "kind": "ODDS_JOURNAL", "sequence": int(self.count), "settlementReady": False})
        self.snapshots[self.count] = _canonical(result)
        self.count = u256(int(self.count) + 1)
        self.last_slot = u256(slot)

    @gl.public.view
    def get_snapshot(self, index: int) -> str:
        if index < 0 or index >= int(self.count):
            raise gl.vm.UserError("INVALID_SNAPSHOT")
        return self.snapshots[u256(index)]

    @gl.public.view
    def get_count(self) -> int:
        return int(self.count)

`);
}
